POST http://localhost:3000/api/v1/signup
Content-Type: application/json

{
    "username":"human11@gmail.com",
    "password":"pass123",
    "type":"user"
}
###

POST http://localhost:3000/api/v1/signin
Content-Type: application/json

{
    "username":"human11@gmail.com",
    "password":"pass123"
}
###

POST http://localhost:3000/api/v1/user/metadata
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbTlwamtta2wwMDFscXB2MGlnYWQxbHVkIiwicm9sZSI6IkFkbWluIiwiaWF0IjoxNzQ1MTU1NTc2LCJleHAiOjE3NDUxNTkxNzZ9.yCg0-Tro2eXwU9NWHyfM2437QLdZhvr6kiNKJ9HKitw

{
    "avatarId": "cm9pj94tt0004qpv00ophkwod"
}
###
GET http://localhost:3000/api/v1/user/getuserdetails
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWJxbzNldzcwMDAwcXB5ZzBsY284ODU1Iiwicm9sZSI6IlVzZXIiLCJpYXQiOjE3NDk1NzQ5NDgsImV4cCI6MTc0OTU3ODU0OH0.7QKd0Wfdtc_Kmo_NGoqRT3VjOJXGuiOAjPU9eRrztDU
