FROM node:18-alpine AS BUILDER
WORKDIR /app

COPY package*.json ./
COPY apps/frontend ./apps/frontend
COPY packages ./packages

RUN npm install
WORKDIR /app/apps/frontend

RUN npm run build

FROM node:18-alpine
WORKDIR /app

COPY --from=builder /app/apps/frontend/dist ./dist
RUN npm install -g vite

EXPOSE 5173

CMD ["vite", "preview", "--port", "5173", "--host"]